### ISSUE TITLE
VDCT doesn't handle escaped double-quotes, or escape back-slashes

### ISSUE THREAD

**Issue by anjohnson** [epics-extensions/VisualDCT#11]
I used vdct 2.6.1274 to set a DESC field to `"Hello"` with quote characters at each end. It correctly escaped the quotes on saving, giving me this:

```
  field(DESC, "\"Hello\"")
```

However when I read that .vdb file back into vdct the inspector only showed a single back-slash character in that field, and on saving the file again, the result was this:

```
  field(DESC, "\")
```

That isn't a properly escaped back-slash character either, although the IOC does read it in properly as long as it's at the end of a string.

I haven't tested these issues with the latest version of vdct, but properly handling back-slashes and escaped quotes in .db files is going to be essential in the future so this bug is pretty important.

**Comment by ralphlange** [comment]
Note that this is Java, so do not use any escape characters inside the application, they will be added/consumed as part of file IO.
