### ISSUE TITLE
Save UTF-8 db files.

### ISSUE THREAD

**Issue by lcavalli** [epics-extensions/VisualDCT#13]
Hi,

I have a db file with UTF-8 charset encoding (I need to use μm engineering unit).
While VisualDCT can open the file without problems, it is not able to save it in the same format.
I already added the option -Dfile.encoding=UTF-8 to the command line in runScript.
Is there a way to force UTF-8 file encoding?

Luca

**Comment by ralphlange** [comment]
In EPICS in general, using UTF-8 (and especially multi-byte characters) you are prettly much on thin ice - and on your own.
EPICS Base is completely agnostic to encoding, so the user is responsible for making sure the encoding is consistent across all IOCs and clients. Also, the EPICS string manipulation routines will happily cut multi-byte characters in pieces, creating invalid strings.

Using µ or the degree sign In fields that are not manipulated (like EGU) is usually safe, though.
Looks funny on ASCII terminals, be warned.
