### ISSUE TITLE
Management of a record with a field VAL with no quote value

### ISSUE THREAD

**Issue by katysaintin** [epics-extensions/VisualDCT#21]
Hello,

I'm using the VisualDCT library in our EPICS project. (IRFU , LDISC laboratory at CEA Saclay).
There is a problème when a EPICS records have a field VAL with an integer value.
Ex : 
record(ao, "MY-PV-NAME"){
 **field(VAL, 0)**
 field(PINI, "YES")
 field(DTYP, "S7plc")
 field(DESC, "My description")
 field(OUT, "@PLCName/0 T=FLOAT")
}

The first problem is that VDCTSend a DBParserException ""Invalid field value...". Because it only manage value within the quote ex : "0" (EPICS IOC can deal without the quotes.

The second problem is that is a integer value, the token send back a double value. So it will send 0.0 instead of 0.

Please find my fix proposition in attachement.

[test.db.txt](https://github.com/epics-extensions/VisualDCT/files/2062984/test.db.txt)
[DBResolver.java.txt](https://github.com/epics-extensions/VisualDCT/files/2062985/DBResolver.java.txt)
[EnhancedStreamTokenizer.java.txt](https://github.com/epics-extensions/VisualDCT/files/2062987/EnhancedStreamTokenizer.java.txt)

Best regards,

Katy SAINTIN
___________________________________________________
Ingénieur chercheur en développement logiciel
Laboratoire de Développement et Intégration de Systèmes de Contrôle
DRF/IRFU/DIS/LDISC CEA de Saclay

**Comment by ralphlange** [comment]
Hi Katy,
the VAL field of the ao (analog output) record is of type double. Representing a double value in the db file as a number in floating point format seems very appropriate.
For integer values, the longout record is the more appropriate type. Its value is an integer and will be represented in the db file as an integer.

**Comment by katysaintin** [comment]
Ok thanks, yes you're right :) 
I make a mistake in my sample test.db

If your record is 

record(ao, "MY-PV-NAME"){
 field(VAL, 0)
 field(PINI, "YES")
 field(DTYP, "S7plc")
 field(DESC, "My description")
 field(OUT, "@PLCName/0 T=INT")
}

When you get nval, it's return 0.0 because nval is a double, an I want to keep the data precision.
That why I keep, sval as a value in my project.

Anyway, I let you deal with this code proposition :)  . Thanks for you help. And have a very nice week-end.

Katy

**Comment by ralphlange** [comment]
Sorry, I am getting confused here... What are nval and sval? I am also not 100% sure what you mean by "return 0.0".
Can you describe what you try to do, and where you think it fails?

**Comment by katysaintin** [comment]
OK sorry : ), I'm nval and sval is the variable in the EnhancedStreamTokenizer.java class.

But anyway. What I'm try to do is to load test.db file with VisualDCT .
It's return an exception"Invalid field value..."  because the field 👍 
field(VAL, 0) contains no quote =>as it field(VAL, "0")
The code source I send (DBResolver.java.txt EnhancedStreamTokenizer.java.txt) manage this case. 

Cheers .

Katy

**Comment by katysaintin** [comment]
Perhaps It will more convenient to discuss in french ?

**Comment by ralphlange** [comment]
Can try. Email me at ralph.lange@gmx.de, and I will try my best...

**Comment by katysaintin** [comment]
Hello Ralph, it's OK now for us. Thanks a lot.

Katy
