### ISSUE TITLE
Building Fails

### ISSUE THREAD

**Issue by es-sns121** [epics-extensions/VisualDCT#23]
When building 
    
    mvn clean install

The build fails due to Java 1.5 no longer being supported.

    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] error: Source option 5 is no longer supported. Use 6 or later.
    [ERROR] error: Target option 1.5 is no longer supported. Use 1.6 or later.

adding the following to the pom.xml file allowed the build to advance.
    
    <properties>
      ....
      <maven.compiler.source>1.6</maven.compiler.source>
      <maven.compiler.target>1.6</maven.compiler.target>
    </properties>

The build also fails due to Javadoc errors.

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:jar (attach-javadocs) on project VisualDCT: MavenReportException: Error while creating archive:
    [ERROR] Exit code: 1 - javadoc: warning - You have not specified the version of HTML to use.
    [ERROR] The default is currently HTML 4.01, but this will change to HTML5
    [ERROR] in a future release. To suppress this warning, please specify the
    [ERROR] version of HTML used in your documentation comments and to be
    [ERROR] generated by this doclet, using the -html4 or -html5 options.
    [ERROR] VisualDCT/src/main/java/com/cosylab/vdct/DBDDialog.java:60: error: unknown tag: author:
    [ERROR] * @author:
    [ERROR] ^
    [ERROR] VisualDCT/src/main/java/com/cosylab/vdct/about/AboutDialogEngine.java:34: error: unknown tag: author:
    [ERROR] * @author:
    [ERROR] ^
    [ERROR] VisualDCT/src/main/java/com/cosylab/vdct/about/AboutDialog.java:34: error: unknown tag: author:
    [ERROR] * @author:
    [ERROR] ^
    [ERROR] VisualDCT/src/main/java/com/cosylab/vdct/db/DBConnectorData.java:34: warning: no description for @author
    [ERROR] * @author
    [ERROR] ^
    .......

Simply skipping building the javadocs allowed the build to succeed.

    mvn clean install -Dmaven.javadoc.skip=true

However, the runScript does not work... Still working on this.

**Comment by ralphlange** [comment]
What version of Java are you using?
Support for 1.5 was dropped in Java 9, which also is a lot pickier when it comes to Javadoc.

**Comment by ralphlange** [comment]
Note also that neither the JDK version nor the source and target options are defined within the project.
In that case a failing build would rather point to an issue in your setup, wouldn't it?

**Comment by es-sns121** [comment]
Ah, that would explain it. I am using Java 10.

**Comment by ralphlange** [comment]
Can you verify that current master builds and successfully creates Javadoc on your Java 10 install?

**Comment by es-sns121** [comment]
It builds successfully!

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 23.361s
    [INFO] Finished at: Mon Aug 13 11:40:55 EDT 2018
    [INFO] Final Memory: 27M/100M
    [INFO] ------------------------------------------------------------------------

**Comment by es-sns121** [comment]
Running 

    sh runScript

still results in 

    Error: Could not find or load main class com.cosylab.vdct.VisualDCT
    Caused by: java.lang.ClassNotFoundException: com.cosylab.vdct.VisualDCT

however 

    java -jar target/VisualDCT-2.7.1-SNAPSHOT.jar

successfully opens the VisualDCT and it works as expected.

Thanks for your help.

**Comment by ralphlange** [comment]
That "failure" of the run script is actually expected, as using the "-cp" version of starting the application needs the jar to be added to the Java classpath (environment variable).

See the "[Running VisualDCT](https://epics-extensions.github.io/VisualDCT/doc/MAN-VisualDCT_Users_Manual.html#running)" chapter in the User's Manual.

Closing the issue.
